-- 공정 라우팅 샘플 데이터 생성
-- 4개 라우팅: 반제품 1개 + 완제품 3개

-- 1. 반제품 라우팅 (오이 비누 베이스) - 4단계
INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0001', 'SE001', '원료 혼합', '혼합', 1, 'mix.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0002', 'SE001', '비누 베이스 제조', '성형', 2, 'mold.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0003', 'SE001', '건조', '건조', 3, 'dry.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0004', 'SE001', '베이스 포장', '포장', 4, 'package.png', SYSDATE, SYSDATE);

-- 2. 완제품 라우팅 1 (오이 천연비누) - 8단계
INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0005', 'FI001', '성분 추가', '혼합', 1, 'extract.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0006', 'FI001', '비누 베이스 혼합', '혼합', 2, 'mix.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0007', 'FI001', '성형 및 건조', '성형', 3, 'mold.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0008', 'FI001', '포장', '포장', 4, 'package.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0009', 'FI001', '추가 성분 배합', '혼합', 5, 'extract.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0010', 'FI001', '최종 혼합', '혼합', 6, 'mix.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0011', 'FI001', '완제품 성형', '성형', 7, 'mold.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0012', 'FI001', '완제품 포장', '포장', 8, 'package.png', SYSDATE, SYSDATE);

-- 3. 완제품 라우팅 2 (오이 각질제거비누) - 8단계
INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0013', 'FI002', '각질제거 성분 추가', '혼합', 1, 'extract.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0014', 'FI002', '각질제거 성분 혼합', '혼합', 2, 'mix.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0015', 'FI002', '각질제거 성형', '성형', 3, 'mold.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0016', 'FI002', '각질제거 포장', '포장', 4, 'package.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0017', 'FI002', '추가 각질제거 성분', '혼합', 5, 'extract.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0018', 'FI002', '최종 각질제거 혼합', '혼합', 6, 'mix.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0019', 'FI002', '각질제거 완제품 성형', '성형', 7, 'mold.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0020', 'FI002', '각질제거 완제품 포장', '포장', 8, 'package.png', SYSDATE, SYSDATE);

-- 4. 완제품 라우팅 3 (오이 수축비누) - 8단계
INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0021', 'FI003', '수축 성분 추가', '혼합', 1, 'extract.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0022', 'FI003', '수축 성분 혼합', '혼합', 2, 'mix.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0023', 'FI003', '수축 성형', '성형', 3, 'mold.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0024', 'FI003', '수축 포장', '포장', 4, 'package.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0025', 'FI003', '추가 수축 성분', '혼합', 5, 'extract.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0026', 'FI003', '최종 수축 혼합', '혼합', 6, 'mix.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0027', 'FI003', '수축 완제품 성형', '성형', 7, 'mold.png', SYSDATE, SYSDATE);

INSERT INTO PROCESS (PROCESS_NO, STANDARD_CODE, PR_DESCRIPTION, PR_TYPE, PR_ORDER, PR_IMAGE, CREATE_DATE, UPDATE_DATE) 
VALUES ('PC0028', 'FI003', '수축 완제품 포장', '포장', 8, 'package.png', SYSDATE, SYSDATE);

-- 데이터 확인 쿼리
SELECT 
    p.STANDARD_CODE,
    s.ST_NAME,
    s.ST_TYPE,
    COUNT(p.PROCESS_NO) as PROCESS_COUNT,
    MIN(p.PR_ORDER) as MIN_ORDER,
    MAX(p.PR_ORDER) as MAX_ORDER
FROM PROCESS p
JOIN STANDARD s ON p.STANDARD_CODE = s.STANDARD_CODE
WHERE s.ST_TYPE IN ('SEMI', 'FINISH')
GROUP BY p.STANDARD_CODE, s.ST_NAME, s.ST_TYPE
ORDER BY s.ST_TYPE, s.ST_NAME;
