CREATE TABLE `PRODUCTION_HISTORY` (
	`HISTORY_ID`	integer	NULL,
	`RAW_LOT_ID`	integer	NULL,
	`SEMI_LOT_ID`	integer	NULL	COMMENT '반제품',
	`FINISHED_LOT_ID`	integer	NULL	COMMENT '완제품',
	`STEP_NAME`	varchar(100)	NULL	COMMENT '공정',
	`START_TIME`	date	NULL	COMMENT '시작',
	`END_TIME`	date	NULL	COMMENT '종료',
	`OPERATOR`	varchar(100)	NULL	COMMENT '작업자',
	`STATUS`	varchar(20)	NULL	COMMENT '상태'
);

CREATE TABLE `WORKERS` (
	`WORKER_ID`	integer	NULL,
	`USER_ID`	integer	NULL,
	`WORKER_NAME`	varchar(100)	NOT NULL	COMMENT '작업자명',
	`CURRENT_PROCESS`	varchar(100)	NULL	COMMENT '현재',
	`SKILL_LEVEL`	varchar(20)	NULL	COMMENT 'BEGINNER/INTERMEDIATE/EXPERT',
	`WORK_SHIFT`	varchar(20)	NULL	COMMENT 'DAY/NIGHT',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `WORK_ORDER_PROCESS` (
	`WORK_ORDER_PROCESS_ID`	integer	NULL,
	`WORK_ORDER_ID`	integer	NULL,
	`PROCESS_SEQUENCE`	integer	NOT NULL	COMMENT '공정',
	`PROCESS_NAME`	varchar(100)	NOT NULL	COMMENT '공정명',
	`PROCESS_CODE`	varchar(50)	NULL	COMMENT '공정',
	`PLANNED_QUANTITY`	decimal(10,2)	NOT NULL	COMMENT '공정별',
	`ACTUAL_QUANTITY`	decimal(10,2)	NULL	COMMENT '공정별',
	`STANDARD_TIME`	decimal(5,2)	NULL	COMMENT '표준',
	`ACTUAL_TIME`	decimal(5,2)	NULL	COMMENT '실제',
	`EQUIPMENT_ID`	varchar(50)	NULL	COMMENT '사용',
	`EQUIPMENT_NAME`	varchar(100)	NULL	COMMENT '사용',
	`PROCESS_PARAMETERS`	text	NULL	COMMENT '공정',
	`STATUS`	varchar(20)	NULL	DEFAULT 'PLANNED'	COMMENT 'PLANNED/IN_PROGRESS/COMPLETED/ON_HOLD',
	`START_TIME`	date	NULL	COMMENT '공정',
	`END_TIME`	date	NULL	COMMENT '공정',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `SEMI_FINISHED_LOT` (
	`SEMI_LOT_ID`	integer	NULL,
	`PRODUCT_ID`	integer	NULL,
	`QUANTITY`	decimal(10,2)	NULL	COMMENT '수량',
	`UNIT`	varchar(10)	NULL	COMMENT '단위',
	`PROCESS_STEP`	varchar(50)	NULL	COMMENT '공정',
	`STATUS`	varchar(20)	NULL	DEFAULT 'IVB'	COMMENT '상태',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `WORK_ORDER` (
	`WORK_ORDER_ID`	integer	NULL,
	`ORDER_ID`	integer	NULL,
	`PRODUCT_ID`	integer	NULL	COMMENT '제품',
	`WORK_ORDER_NO`	varchar(50)	NOT NULL	COMMENT '작업지시',
	`WORK_ORDER_TYPE`	varchar(20)	NOT NULL	COMMENT 'PRODUCTION/REPAIR/MAINTENANCE',
	`PLANNED_QUANTITY`	decimal(10,2)	NOT NULL	COMMENT '계획',
	`ACTUAL_QUANTITY`	decimal(10,2)	NULL	COMMENT '실제',
	`PRIORITY`	varchar(20)	NULL	DEFAULT 'NORMAL'	COMMENT 'HIGH/NORMAL/LOW',
	`STATUS`	varchar(20)	NULL	DEFAULT 'PLANNED'	COMMENT 'PLANNED/IN_PROGRESS/COMPLETED/CANCELLED',
	`PLANNED_START_DATE`	date	NULL	COMMENT '계획',
	`PLANNED_END_DATE`	date	NULL	COMMENT '계획',
	`ACTUAL_START_DATE`	date	NULL	COMMENT '실제',
	`ACTUAL_END_DATE`	date	NULL	COMMENT '실제',
	`CREATED_BY`	integer	NULL	COMMENT '생성자',
	`CREATED_AT`	date	NULL	COMMENT '생성일',
	`UPDATED_AT`	date	NULL	COMMENT '수정일'
);

CREATE TABLE `SEMI_TO_FINISHED_BOM` (
	`SEMI_FINISHED_BOM_ID`	integer	NULL,
	`PARENT_ID`	integer	NULL,
	`CHILD_ID`	integer	NULL	COMMENT '반제품',
	`QUANTITY`	decimal(10,2)	NOT NULL	COMMENT '필요',
	`MIXING_RATIO`	decimal(5,2)	NULL	COMMENT '배합',
	`CURING_TIME`	decimal(5,2)	NULL	COMMENT '숙성',
	`PACKAGING_TYPE`	varchar(50)	NULL	COMMENT '포장',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `FINISHED_PRODUCT_LOT` (
	`FINISHED_LOT_ID`	integer	NULL,
	`PRODUCT_ID`	integer	NULL,
	`QUANTITY`	integer	NULL	COMMENT '수량',
	`QC_STATUS`	varchar(20)	NULL	DEFAULT 'PENDING'	COMMENT '품질검사',
	`INSPECTOR`	varchar(100)	NULL	COMMENT '검사자',
	`STATUS`	varchar(20)	NULL	DEFAULT 'IVB'	COMMENT '상태',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `RAW_TO_SEMI_BOM` (
	`RAW_SEMI_BOM_ID`	integer	NULL,
	`PARENT_ID`	integer	NULL,
	`CHILD_ID`	integer	NULL	COMMENT '원자재',
	`QUANTITY`	decimal(10,2)	NOT NULL	COMMENT '필요',
	`PROCESS_TEMP`	decimal(5,2)	NULL	COMMENT '공정',
	`PROCESS_TIME`	decimal(5,2)	NULL	COMMENT '공정',
	`EQUIPMENT`	varchar(50)	NULL	COMMENT '사용',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `ORDERS` (
	`ORDER_ID`	integer	NULL,
	`CUSTOMER_ID`	integer	NULL,
	`PRODUCT_ID`	integer	NULL	COMMENT '제품',
	`FINISHED_LOT_ID`	integer	NULL	COMMENT '완제품',
	`QUANTITY`	integer	NULL	COMMENT '주문',
	`ORDER_DATE`	date	NULL	COMMENT '주문일',
	`STATUS`	varchar(20)	NULL	DEFAULT 'PENDING'	COMMENT '주문'
);

CREATE TABLE `CUSTOMER` (
	`CUSTOMER_ID`	integer	NULL,
	`NAME`	varchar(100)	NOT NULL,
	`CONTACT`	varchar(100)	NULL	COMMENT '연락처',
	`ADDRESS`	varchar(200)	NULL	COMMENT '주소'
);

CREATE TABLE `RAW_MATERIAL_LOT` (
	`RAW_LOT_ID`	integer	NULL,
	`PRODUCT_ID`	integer	NULL,
	`QUANTITY`	decimal(10,2)	NULL	COMMENT '수량',
	`UNIT`	varchar(10)	NULL	COMMENT '단위',
	`SUPPLIER`	varchar(100)	NULL	COMMENT '공급업체',
	`EXPIRY_DATE`	date	NULL	COMMENT '유통기한',
	`STATUS`	varchar(20)	NULL	DEFAULT 'IVB'	COMMENT '상태',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `WORK_ORDER_MATERIAL` (
	`WORK_ORDER_MATERIAL_ID`	integer	NULL,
	`WORK_ORDER_ID`	integer	NULL,
	`WORK_ORDER_PROCESS_ID`	integer	NULL	COMMENT '공정',
	`PRODUCT_ID`	integer	NULL	COMMENT '자재',
	`MATERIAL_TYPE`	varchar(20)	NOT NULL	COMMENT 'RAW/SEMI_FINISHED',
	`LOT_ID`	integer	NULL	COMMENT 'LOT',
	`PLANNED_QUANTITY`	decimal(10,2)	NOT NULL	COMMENT '계획',
	`ACTUAL_QUANTITY`	decimal(10,2)	NULL	COMMENT '실제',
	`UNIT`	varchar(20)	NULL	COMMENT '단위',
	`STATUS`	varchar(20)	NULL	DEFAULT 'PLANNED'	COMMENT 'PLANNED/ISSUED/USED/RETURNED',
	`ISSUE_DATE`	date	NULL	COMMENT '자재',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `PASSWORD_HISTORY` (
	`HISTORY_ID`	integer	NULL,
	`USER_ID`	integer	NULL,
	`PASSWORD`	varchar(100)	NOT NULL	COMMENT '이전',
	`CHANGED_AT`	date	NULL	COMMENT '변경일'
);

CREATE TABLE `USERS` (
	`USER_ID`	integer	NULL,
	`EMPLOYEE_NUMBER`	varchar(20)	NOT NULL,
	`USERNAME`	varchar(50)	NOT NULL	COMMENT '사용자명',
	`PASSWORD`	varchar(100)	NOT NULL	COMMENT '비밀번호',
	`ROLE`	varchar(20)	NULL	DEFAULT 'EMPLOYEE'	COMMENT 'ADMIN/EMPLOYEE',
	`IS_FIRST_LOGIN`	integer	NULL	COMMENT '최초',
	`IS_ACTIVE`	integer	NULL	COMMENT '계정',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `KPI` (
	`KPI_ID`	integer	NULL,
	`PRODUCT_ID`	integer	NULL,
	`KPI_NAME`	varchar(100)	NOT NULL	COMMENT 'KPI',
	`KPI_TYPE`	varchar(20)	NULL	COMMENT 'PRODUCTIVITY/QUALITY/EFFICIENCY',
	`TARGET_VALUE`	integer	NULL	COMMENT '목표값',
	`ACTUAL_VALUE`	integer	NULL	COMMENT '실제값',
	`MEASURE_DATE`	date	NULL	COMMENT '측정일'
);

CREATE TABLE `WORK_ORDER_WORKER` (
	`WORK_ORDER_WORKER_ID`	integer	NULL,
	`WORK_ORDER_ID`	integer	NULL,
	`WORK_ORDER_PROCESS_ID`	integer	NULL	COMMENT '공정',
	`WORKER_ID`	integer	NULL	COMMENT '작업자',
	`ROLE`	varchar(50)	NULL	COMMENT 'OPERATOR/SUPERVISOR/INSPECTOR',
	`ASSIGNED_DATE`	date	NULL	COMMENT '할당일',
	`START_TIME`	date	NULL	COMMENT '작업',
	`END_TIME`	date	NULL	COMMENT '작업',
	`STATUS`	varchar(20)	NULL	DEFAULT 'ASSIGNED'	COMMENT 'ASSIGNED/IN_PROGRESS/COMPLETED',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `PRODUCT` (
	`PRODUCT_ID`	integer	NULL,
	`PRODUCT_NAME`	varchar(100)	NOT NULL,
	`PRODUCT_TYPE`	varchar(20)	NOT NULL,
	`UNIT`	varchar(20)	NULL	COMMENT 'kg',
	`DESCRIPTION`	varchar(500)	NULL	COMMENT '제품'
);

CREATE TABLE `SEMI_FINISHED_BOM_LOT` (
	`SEMI_FINISHED_BOM_LOT_ID`	integer	NULL,
	`SEMI_FINISHED_BOM_ID`	integer	NULL,
	`SEMI_LOT_ID`	integer	NULL	COMMENT '반제품',
	`FINISHED_LOT_ID`	integer	NULL	COMMENT '완제품',
	`PLANNED_QUANTITY`	decimal(10,2)	NULL	COMMENT '계획',
	`ACTUAL_QUANTITY`	decimal(10,2)	NULL	COMMENT '실제',
	`VARIANCE`	decimal(10,2)	NULL	COMMENT '차이',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

CREATE TABLE `RAW_SEMI_BOM_LOT` (
	`RAW_SEMI_BOM_LOT_ID`	integer	NULL,
	`RAW_SEMI_BOM_ID`	integer	NULL,
	`RAW_LOT_ID`	integer	NULL	COMMENT '원자재',
	`SEMI_LOT_ID`	integer	NULL	COMMENT '반제품',
	`PLANNED_QUANTITY`	decimal(10,2)	NULL	COMMENT '계획',
	`ACTUAL_QUANTITY`	decimal(10,2)	NULL	COMMENT '실제',
	`VARIANCE`	decimal(10,2)	NULL	COMMENT '차이',
	`CREATED_AT`	date	NULL	COMMENT '생성일'
);

ALTER TABLE `PRODUCTION_HISTORY` ADD CONSTRAINT `FK_RAW_MATERIAL_LOT_TO_PRODUCTION_HISTORY_1` FOREIGN KEY (
	`RAW_LOT_ID`
)
REFERENCES `RAW_MATERIAL_LOT` (
	`RAW_LOT_ID`
);

ALTER TABLE `PRODUCTION_HISTORY` ADD CONSTRAINT `FK_SEMI_FINISHED_LOT_TO_PRODUCTION_HISTORY_1` FOREIGN KEY (
	`SEMI_LOT_ID`
)
REFERENCES `SEMI_FINISHED_LOT` (
	`SEMI_LOT_ID`
);

ALTER TABLE `PRODUCTION_HISTORY` ADD CONSTRAINT `FK_FINISHED_PRODUCT_LOT_TO_PRODUCTION_HISTORY_1` FOREIGN KEY (
	`FINISHED_LOT_ID`
)
REFERENCES `FINISHED_PRODUCT_LOT` (
	`FINISHED_LOT_ID`
);

ALTER TABLE `WORKERS` ADD CONSTRAINT `FK_USERS_TO_WORKERS_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `WORK_ORDER_PROCESS` ADD CONSTRAINT `FK_WORK_ORDER_TO_WORK_ORDER_PROCESS_1` FOREIGN KEY (
	`WORK_ORDER_ID`
)
REFERENCES `WORK_ORDER` (
	`WORK_ORDER_ID`
);

ALTER TABLE `SEMI_FINISHED_LOT` ADD CONSTRAINT `FK_PRODUCT_TO_SEMI_FINISHED_LOT_1` FOREIGN KEY (
	`PRODUCT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `WORK_ORDER` ADD CONSTRAINT `FK_ORDERS_TO_WORK_ORDER_1` FOREIGN KEY (
	`ORDER_ID`
)
REFERENCES `ORDERS` (
	`ORDER_ID`
);

ALTER TABLE `WORK_ORDER` ADD CONSTRAINT `FK_PRODUCT_TO_WORK_ORDER_1` FOREIGN KEY (
	`PRODUCT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `WORK_ORDER` ADD CONSTRAINT `FK_USERS_TO_WORK_ORDER_1` FOREIGN KEY (
	`CREATED_BY`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `SEMI_TO_FINISHED_BOM` ADD CONSTRAINT `FK_PRODUCT_TO_SEMI_TO_FINISHED_BOM_1` FOREIGN KEY (
	`PARENT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `SEMI_TO_FINISHED_BOM` ADD CONSTRAINT `FK_PRODUCT_TO_SEMI_TO_FINISHED_BOM_2` FOREIGN KEY (
	`CHILD_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `FINISHED_PRODUCT_LOT` ADD CONSTRAINT `FK_PRODUCT_TO_FINISHED_PRODUCT_LOT_1` FOREIGN KEY (
	`PRODUCT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `RAW_TO_SEMI_BOM` ADD CONSTRAINT `FK_PRODUCT_TO_RAW_TO_SEMI_BOM_1` FOREIGN KEY (
	`PARENT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `RAW_TO_SEMI_BOM` ADD CONSTRAINT `FK_PRODUCT_TO_RAW_TO_SEMI_BOM_2` FOREIGN KEY (
	`CHILD_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_CUSTOMER_TO_ORDERS_1` FOREIGN KEY (
	`CUSTOMER_ID`
)
REFERENCES `CUSTOMER` (
	`CUSTOMER_ID`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_PRODUCT_TO_ORDERS_1` FOREIGN KEY (
	`PRODUCT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_FINISHED_PRODUCT_LOT_TO_ORDERS_1` FOREIGN KEY (
	`FINISHED_LOT_ID`
)
REFERENCES `FINISHED_PRODUCT_LOT` (
	`FINISHED_LOT_ID`
);

ALTER TABLE `RAW_MATERIAL_LOT` ADD CONSTRAINT `FK_PRODUCT_TO_RAW_MATERIAL_LOT_1` FOREIGN KEY (
	`PRODUCT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `WORK_ORDER_MATERIAL` ADD CONSTRAINT `FK_WORK_ORDER_TO_WORK_ORDER_MATERIAL_1` FOREIGN KEY (
	`WORK_ORDER_ID`
)
REFERENCES `WORK_ORDER` (
	`WORK_ORDER_ID`
);

ALTER TABLE `WORK_ORDER_MATERIAL` ADD CONSTRAINT `FK_WORK_ORDER_PROCESS_TO_WORK_ORDER_MATERIAL_1` FOREIGN KEY (
	`WORK_ORDER_PROCESS_ID`
)
REFERENCES `WORK_ORDER_PROCESS` (
	`WORK_ORDER_PROCESS_ID`
);

ALTER TABLE `WORK_ORDER_MATERIAL` ADD CONSTRAINT `FK_PRODUCT_TO_WORK_ORDER_MATERIAL_1` FOREIGN KEY (
	`PRODUCT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `PASSWORD_HISTORY` ADD CONSTRAINT `FK_USERS_TO_PASSWORD_HISTORY_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`USER_ID`
);

ALTER TABLE `KPI` ADD CONSTRAINT `FK_PRODUCT_TO_KPI_1` FOREIGN KEY (
	`PRODUCT_ID`
)
REFERENCES `PRODUCT` (
	`PRODUCT_ID`
);

ALTER TABLE `WORK_ORDER_WORKER` ADD CONSTRAINT `FK_WORK_ORDER_TO_WORK_ORDER_WORKER_1` FOREIGN KEY (
	`WORK_ORDER_ID`
)
REFERENCES `WORK_ORDER` (
	`WORK_ORDER_ID`
);

ALTER TABLE `WORK_ORDER_WORKER` ADD CONSTRAINT `FK_WORK_ORDER_PROCESS_TO_WORK_ORDER_WORKER_1` FOREIGN KEY (
	`WORK_ORDER_PROCESS_ID`
)
REFERENCES `WORK_ORDER_PROCESS` (
	`WORK_ORDER_PROCESS_ID`
);

ALTER TABLE `WORK_ORDER_WORKER` ADD CONSTRAINT `FK_WORKERS_TO_WORK_ORDER_WORKER_1` FOREIGN KEY (
	`WORKER_ID`
)
REFERENCES `WORKERS` (
	`WORKER_ID`
);

ALTER TABLE `SEMI_FINISHED_BOM_LOT` ADD CONSTRAINT `FK_RAW_TO_SEMI_BOM_TO_SEMI_FINISHED_BOM_LOT_1` FOREIGN KEY (
	`SEMI_FINISHED_BOM_ID`
)
REFERENCES `RAW_TO_SEMI_BOM` (
	`RAW_SEMI_BOM_ID`
);

ALTER TABLE `SEMI_FINISHED_BOM_LOT` ADD CONSTRAINT `FK_SEMI_FINISHED_LOT_TO_SEMI_FINISHED_BOM_LOT_1` FOREIGN KEY (
	`SEMI_LOT_ID`
)
REFERENCES `SEMI_FINISHED_LOT` (
	`SEMI_LOT_ID`
);

ALTER TABLE `SEMI_FINISHED_BOM_LOT` ADD CONSTRAINT `FK_FINISHED_PRODUCT_LOT_TO_SEMI_FINISHED_BOM_LOT_1` FOREIGN KEY (
	`FINISHED_LOT_ID`
)
REFERENCES `FINISHED_PRODUCT_LOT` (
	`FINISHED_LOT_ID`
);

ALTER TABLE `RAW_SEMI_BOM_LOT` ADD CONSTRAINT `FK_RAW_TO_SEMI_BOM_TO_RAW_SEMI_BOM_LOT_1` FOREIGN KEY (
	`RAW_SEMI_BOM_ID`
)
REFERENCES `RAW_TO_SEMI_BOM` (
	`RAW_SEMI_BOM_ID`
);

ALTER TABLE `RAW_SEMI_BOM_LOT` ADD CONSTRAINT `FK_RAW_MATERIAL_LOT_TO_RAW_SEMI_BOM_LOT_1` FOREIGN KEY (
	`RAW_LOT_ID`
)
REFERENCES `RAW_MATERIAL_LOT` (
	`RAW_LOT_ID`
);

ALTER TABLE `RAW_SEMI_BOM_LOT` ADD CONSTRAINT `FK_SEMI_FINISHED_LOT_TO_RAW_SEMI_BOM_LOT_1` FOREIGN KEY (
	`SEMI_LOT_ID`
)
REFERENCES `SEMI_FINISHED_LOT` (
	`SEMI_LOT_ID`
);

