-- MES 비누 생산 시스템 데이터베이스 생성
-- Oracle Database 기준

-- 1. 기준관리 테이블 생성
CREATE TABLE STANDARD (
    STANDARD_CODE VARCHAR2(3000) PRIMARY KEY,    -- 제품코드 (RA0001, SE0001, FI0001)
    ST_TYPE VARCHAR2(3000) NOT NULL,             -- 제품유형 (원자제, 반제품, 완제품)
    ST_NAME VARCHAR2(3000) NOT NULL,             -- 제품 이름
    ST_QUANTITY NUMBER DEFAULT 0,                -- 제품 갯수
    ST_UNIT VARCHAR2(3000),                      -- 제품 단위
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 2. 생산관리 테이블 생성
CREATE TABLE PRODUCTION (
    PRODUCTION_NO VARCHAR2(3000) PRIMARY KEY,    -- 생산번호 (P0001)
    STANDARD_CODE VARCHAR2(3000) NOT NULL,       -- 제품코드 (FK)
    EMPLOYEE_NO VARCHAR2(3000),                  -- 담당자 (FK)
    PR_START DATE,                               -- 생산 시작일
    PR_END DATE,                                 -- 생산 종료일
    PR_TARGET NUMBER,                            -- 생산 목표량
    PR_COMPLETED NUMBER DEFAULT 0,               -- 생산 완료량
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 3. 작업관리 테이블 생성
CREATE TABLE WORK (
    WORK_NO VARCHAR2(3000) PRIMARY KEY,          -- 작업번호 (W0001)
    PRODUCTION_NO VARCHAR2(3000) NOT NULL,       -- 생산번호 (FK)
    STANDARD_CODE VARCHAR2(3000) NOT NULL,       -- 제품코드 (FK)
    EMPLOYEE_NO VARCHAR2(3000),                  -- 담당자 (FK)
    WO_SCHEDULE DATE,                            -- 작업 일정
    WO_QUANTITY NUMBER,                          -- 작업량
    WO_STATUS VARCHAR2(3000) DEFAULT '진행중',    -- 작업 상태
    WO_COMPLETED NUMBER DEFAULT 0,               -- 작업 완료량
    WO_START DATE,                               -- 작업 시작일
    WO_END DATE,                                 -- 작업 종료일
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 4. 품질관리 테이블 생성
CREATE TABLE QUALITY (
    QUALITY_NO VARCHAR2(3000) PRIMARY KEY,       -- 검사번호 (I0001)
    WORK_NO VARCHAR2(3000) NOT NULL,             -- 작업번호 (FK)
    STANDARD_CODE VARCHAR2(3000) NOT NULL,       -- 제품코드 (FK)
    EMPLOYEE_NO VARCHAR2(3000),                  -- 검사자 (FK)
    QU_RESULT VARCHAR2(3000),                    -- 검사 결과 (양품/불량)
    QU_QUANTITY NUMBER,                          -- 양품 수량
    QU_MANUFACTURE_DATE DATE,                    -- 제조일
    DEFECT_QUANTITY NUMBER DEFAULT 0,            -- 불량 수량
    INSPECTION_DATE DATE DEFAULT SYSDATE,        -- 검사일시
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 5. 재고관리 테이블 생성
CREATE TABLE MATERIAL (
    MATERIAL_CODE VARCHAR2(3000) PRIMARY KEY,    -- 재고코드 (MA0001)
    STANDARD_CODE VARCHAR2(3000) NOT NULL,       -- 제품코드 (FK)
    EMPLOYEE_NO VARCHAR2(3000),                  -- 담당자 (FK)
    MA_QUANTITY NUMBER DEFAULT 0,                -- 재고량
    MA_CREATION_DATE DATE DEFAULT SYSDATE,       -- 생성일
    MA_UPDATE_DATE DATE DEFAULT SYSDATE          -- 수정일
);

-- 6. 사용자관리 테이블 생성
CREATE TABLE USERS (
    EMPLOYEE_NO VARCHAR2(3000) PRIMARY KEY,      -- 사원번호 (K0001)
    US_NAME VARCHAR2(3000) NOT NULL,             -- 사용자 이름
    US_POSITION VARCHAR2(3000),                  -- 사용자 직급
    US_EMPLOYEE_NU VARCHAR2(3000) UNIQUE,        -- 사용자 사원번호
    US_PASSWORD VARCHAR2(3000) NOT NULL,         -- 사용자 비밀번호
    US_AUTHORITY VARCHAR2(3000) DEFAULT '사용자', -- 사용자 권한 (관리자/사용자)
    US_PS_UP_STATUS NUMBER DEFAULT 0,            -- 비밀번호 수정 상태
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 7. 게시판관리 테이블 생성
CREATE TABLE BOARD (
    POST_NO VARCHAR2(3000) PRIMARY KEY,          -- 게시글번호 (P0001)
    EMPLOYEE_NO VARCHAR2(3000) NOT NULL,         -- 작성자 (FK)
    BO_CATEGORY VARCHAR2(3000) NOT NULL,         -- 게시판 카테고리
    BO_TITLE VARCHAR2(3000) NOT NULL,            -- 게시판 제목
    BO_CONTENT CLOB,                             -- 게시판 내용
    BO_WRITER VARCHAR2(3000),                    -- 게시판 작성자
    BO_CREATION_DATE DATE DEFAULT SYSDATE,       -- 게시판 작성일
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 8. 공정관리 테이블 생성
CREATE TABLE PROCESS (
    PROCESS_NO VARCHAR2(3000) PRIMARY KEY,       -- 공정번호 (PC0001)
    STANDARD_CODE VARCHAR2(3000) NOT NULL,       -- 제품코드 (FK)
    PR_DESCRIPTION VARCHAR2(3000),               -- 공정 설명
    PR_TYPE VARCHAR2(3000),                      -- 공정 유형 (혼합, 성형, 건조, 포장)
    PR_ORDER NUMBER,                             -- 공정 순서
    PR_IMAGE VARCHAR2(3000),                     -- 공정 이미지
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 9. BOM 관리 테이블 생성
CREATE TABLE BOM (
    BOM_NO VARCHAR2(3000) PRIMARY KEY,           -- BOM번호 (B0001)
    STANDARD_CODE VARCHAR2(3000) NOT NULL,       -- 제품코드 (FK)
    BOM_DESCRIPTION VARCHAR2(3000),              -- BOM 설명
    BOM_TYPE VARCHAR2(3000),                     -- BOM 유형
    BOM_ORDER NUMBER,                            -- BOM 순서
    BOM_IMAGE VARCHAR2(3000),                    -- BOM 이미지
    CREATE_DATE DATE DEFAULT SYSDATE,             -- 생성일
    UPDATE_DATE DATE DEFAULT SYSDATE              -- 수정일
);

-- 외래키 제약조건 추가
ALTER TABLE PRODUCTION ADD CONSTRAINT FK_PRODUCTION_STANDARD 
FOREIGN KEY (STANDARD_CODE) REFERENCES STANDARD(STANDARD_CODE);

ALTER TABLE PRODUCTION ADD CONSTRAINT FK_PRODUCTION_EMPLOYEE 
FOREIGN KEY (EMPLOYEE_NO) REFERENCES USERS(EMPLOYEE_NO);

ALTER TABLE WORK ADD CONSTRAINT FK_WORK_PRODUCTION 
FOREIGN KEY (PRODUCTION_NO) REFERENCES PRODUCTION(PRODUCTION_NO);

ALTER TABLE WORK ADD CONSTRAINT FK_WORK_STANDARD 
FOREIGN KEY (STANDARD_CODE) REFERENCES STANDARD(STANDARD_CODE);

ALTER TABLE WORK ADD CONSTRAINT FK_WORK_EMPLOYEE 
FOREIGN KEY (EMPLOYEE_NO) REFERENCES USERS(EMPLOYEE_NO);

ALTER TABLE QUALITY ADD CONSTRAINT FK_QUALITY_WORK 
FOREIGN KEY (WORK_NO) REFERENCES WORK(WORK_NO);

ALTER TABLE QUALITY ADD CONSTRAINT FK_QUALITY_STANDARD 
FOREIGN KEY (STANDARD_CODE) REFERENCES STANDARD(STANDARD_CODE);

ALTER TABLE QUALITY ADD CONSTRAINT FK_QUALITY_EMPLOYEE 
FOREIGN KEY (EMPLOYEE_NO) REFERENCES USERS(EMPLOYEE_NO);

ALTER TABLE MATERIAL ADD CONSTRAINT FK_MATERIAL_STANDARD 
FOREIGN KEY (STANDARD_CODE) REFERENCES STANDARD(STANDARD_CODE);

ALTER TABLE MATERIAL ADD CONSTRAINT FK_MATERIAL_EMPLOYEE 
FOREIGN KEY (EMPLOYEE_NO) REFERENCES USERS(EMPLOYEE_NO);

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_EMPLOYEE 
FOREIGN KEY (EMPLOYEE_NO) REFERENCES USERS(EMPLOYEE_NO);

ALTER TABLE PROCESS ADD CONSTRAINT FK_PROCESS_STANDARD 
FOREIGN KEY (STANDARD_CODE) REFERENCES STANDARD(STANDARD_CODE);

ALTER TABLE BOM ADD CONSTRAINT FK_BOM_STANDARD 
FOREIGN KEY (STANDARD_CODE) REFERENCES STANDARD(STANDARD_CODE);

-- 시퀀스 생성 (자동증가 번호용)
CREATE SEQUENCE SEQ_STANDARD_CODE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCTION_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_WORK_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_QUALITY_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MATERIAL_CODE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPLOYEE_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POST_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROCESS_NO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOM_NO START WITH 1 INCREMENT BY 1;

-- 테이블 생성 완료 메시지
SELECT 'MES 비누 생산 시스템 데이터베이스 생성이 완료되었습니다.' as MESSAGE FROM DUAL;