-- MES 비누 생산 시스템 테스트 데이터 INSERT - Part 3
-- 작업관리, 품질관리, 재고관리, 게시판관리

-- ========================================
-- 6. 작업관리 (WORK) - 여섯 번째 생성
-- ========================================
-- 오이 천연비누 작업
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-15', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '박작업'), 
 TO_DATE('2025-01-15', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-15 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-15 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-15', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '최작업'), 
 TO_DATE('2025-01-16', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-16 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-16 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-15', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '정작업'), 
 TO_DATE('2025-01-17', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-17 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-17 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-15', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '한작업'), 
 TO_DATE('2025-01-18', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-18 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-18 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-15', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '윤작업'), 
 TO_DATE('2025-01-19', 'YYYY-MM-DD'), 200, '진행중', 50, TO_DATE('2025-01-19 08:00', 'YYYY-MM-DD HH24:MI'), NULL);

-- 오이 각질제거비누 작업
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-16', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '임작업'), 
 TO_DATE('2025-01-16', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-16 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-16 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-16', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '강작업'), 
 TO_DATE('2025-01-17', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-17 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-17 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-16', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '조작업'), 
 TO_DATE('2025-01-18', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-18 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-18 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-16', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '박작업'), 
 TO_DATE('2025-01-19', 'YYYY-MM-DD'), 200, '진행중', 120, TO_DATE('2025-01-19 08:00', 'YYYY-MM-DD HH24:MI'), NULL);

-- 오이 수축비누 작업
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-17', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '최작업'), 
 TO_DATE('2025-01-17', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-17 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-17 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-17', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '정작업'), 
 TO_DATE('2025-01-18', 'YYYY-MM-DD'), 200, '완료', 200, TO_DATE('2025-01-18 08:00', 'YYYY-MM-DD HH24:MI'), TO_DATE('2025-01-18 16:00', 'YYYY-MM-DD HH24:MI'));
INSERT INTO WORK (WORK_NO, PRODUCTION_NO, STANDARD_CODE, EMPLOYEE_NO, WO_SCHEDULE, WO_QUANTITY, WO_STATUS, WO_COMPLETED, WO_START, WO_END) VALUES
('WOR' || LPAD(SEQ_WORK_NO.NEXTVAL, 4, '0'), 
 (SELECT PRODUCTION_NO FROM PRODUCTION WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH') AND PR_START = TO_DATE('2025-01-17', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '한작업'), 
 TO_DATE('2025-01-19', 'YYYY-MM-DD'), 200, '진행중', 80, TO_DATE('2025-01-19 08:00', 'YYYY-MM-DD HH24:MI'), NULL);

-- ========================================
-- 7. 품질관리 (QUALITY) - 일곱 번째 생성
-- ========================================
-- 오이 천연비누 품질 검사
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-15', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 195, TO_DATE('2025-01-15', 'YYYY-MM-DD'), 5, TO_DATE('2025-01-15 16:30', 'YYYY-MM-DD HH24:MI'));
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-16', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 198, TO_DATE('2025-01-16', 'YYYY-MM-DD'), 2, TO_DATE('2025-01-16 16:30', 'YYYY-MM-DD HH24:MI'));
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-17', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 192, TO_DATE('2025-01-17', 'YYYY-MM-DD'), 8, TO_DATE('2025-01-17 16:30', 'YYYY-MM-DD HH24:MI'));
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-18', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 천연비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 196, TO_DATE('2025-01-18', 'YYYY-MM-DD'), 4, TO_DATE('2025-01-18 16:30', 'YYYY-MM-DD HH24:MI'));

-- 오이 각질제거비누 품질 검사
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-16', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 194, TO_DATE('2025-01-16', 'YYYY-MM-DD'), 6, TO_DATE('2025-01-16 16:30', 'YYYY-MM-DD HH24:MI'));
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-17', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 197, TO_DATE('2025-01-17', 'YYYY-MM-DD'), 3, TO_DATE('2025-01-17 16:30', 'YYYY-MM-DD HH24:MI'));
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-18', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 각질제거비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 195, TO_DATE('2025-01-18', 'YYYY-MM-DD'), 5, TO_DATE('2025-01-18 16:30', 'YYYY-MM-DD HH24:MI'));

-- 오이 수축비누 품질 검사
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-17', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 193, TO_DATE('2025-01-17', 'YYYY-MM-DD'), 7, TO_DATE('2025-01-17 16:30', 'YYYY-MM-DD HH24:MI'));
INSERT INTO QUALITY (QUALITY_NO, WORK_NO, STANDARD_CODE, EMPLOYEE_NO, QU_RESULT, QU_QUANTITY, QU_MANUFACTURE_DATE, DEFECT_QUANTITY, INSPECTION_DATE) VALUES
('QUA' || LPAD(SEQ_QUALITY_NO.NEXTVAL, 4, '0'), 
 (SELECT WORK_NO FROM WORK WHERE STANDARD_CODE = (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH') AND WO_SCHEDULE = TO_DATE('2025-01-18', 'YYYY-MM-DD')), 
 (SELECT STANDARD_CODE FROM STANDARD WHERE ST_NAME = '오이 수축비누' AND ST_TYPE = 'FINISH'), 
 (SELECT EMPLOYEE_NO FROM USERS WHERE US_NAME = '이팀장'), 
 '양품', 196, TO_DATE('2025-01-18', 'YYYY-MM-DD'), 4, TO_DATE('2025-01-18 16:30', 'YYYY-MM-DD HH24:MI'));
