-- MES 비누 생산 시스템 테스트 데이터 INSERT - Part 1
-- 외래키 의존성을 고려한 올바른 INSERT 순서 + 시퀀스 사용

--프로젝트에서 등록시 트랜잭션을 이용하여 값을 순차적으로 넣어야함....

-- ========================================
-- 1. 사용자 관리 (USERS) - 먼저 생성 (다른 테이블에서 참조)
-- ========================================
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '김관리', '공장장', 'EMP001', 'admin123', 'ADMIN', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '이팀장', '생산팀장', 'EMP002', 'team123', 'ADMIN', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '박작업', '주임', 'EMP003', 'work123', 'EMPLOYEE', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '최작업', '사원', 'EMP004', 'work123', 'EMPLOYEE', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '정작업', '사원', 'EMP005', 'work123', 'EMPLOYEE', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '한작업', '사원', 'EMP006', 'work123', 'EMPLOYEE', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '윤작업', '사원', 'EMP007', 'work123', 'EMPLOYEE', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '임작업', '사원', 'EMP008', 'work123', 'EMPLOYEE', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '강작업', '사원', 'EMP009', 'work123', 'EMPLOYEE', 1);
INSERT INTO USERS (EMPLOYEE_NO, US_NAME, US_POSITION, US_EMPLOYEE_NU, US_PASSWORD, US_AUTHORITY, US_PS_UP_STATUS) VALUES
('K' || LPAD(SEQ_EMPLOYEE_NO.NEXTVAL, 4, '0'), '조작업', '사원', 'EMP010', 'work123', 'EMPLOYEE', 1);

-- ========================================
-- 2. 기준관리 (STANDARD) - 두 번째 생성 (제품 정보)
-- ========================================
-- 원자재 (RAW)
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '신선 오이', 1000, 'kg');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '가성소다', 500, 'kg');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '팜 오일', 800, 'L');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '올리브 오일', 600, 'L');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '살리실산', 100, 'kg');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '과일산', 80, 'kg');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '아연 PCA', 120, 'kg');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('RA' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'RAW', '티트리 오일', 60, 'L');

-- 반제품 (SEMI)
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('SE' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'SEMI', '오이 추출물', 200, 'L');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('SE' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'SEMI', '비누 베이스', 1500, 'kg');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('SE' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'SEMI', '각질제거 성분', 300, 'kg');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('SE' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'SEMI', '수축 성분', 250, 'kg');

-- 완제품 (FINISH)
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('FI' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'FINISH', '오이 천연비누', 2000, '개');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('FI' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'FINISH', '오이 각질제거비누', 1800, '개');
INSERT INTO STANDARD (STANDARD_CODE, ST_TYPE, ST_NAME, ST_QUANTITY, ST_UNIT) VALUES
('FI' || LPAD(SEQ_STANDARD_CODE.NEXTVAL, 4, '0'), 'FINISH', '오이 수축비누', 1600, '개');
